name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 7
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.345+1
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build

  owo:
    runs-on: ubuntu-latest
    steps:
      - name: do custom shit
        run: ./gradlew hello-world
